music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
	# /music/
    url(r'^$',  views.IndexView.as_view(), name='index'), #index code

    url(r'^register/$',  views.UserFormView.as_view(), name='register'),

    #music/album_id/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # music/album/add/
    url(r'album/add/$', views.AlbumCreate.as_view(), name = 'album-add'),

    # music/album/2/
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name = 'album-update'),

    # music/album/2/delete
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name = 'album-delete'),
]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Album(models.Model):
	artist = models.CharField(max_length=250)
	album_title = models.CharField(max_length=500)
	genre = models.CharField(max_length=100)
	album_logo = models.FileField()
	
	def get_absolute_url(self): 
		return reverse('music:detail', kwargs={'pk': self.pk})

	def __str__(self):
		return self.album_title + ' - ' + self.artist


class Song(models.Model):
	album = models.ForeignKey(Album, on_delete=models.CASCADE)
	file_type = models.CharField(max_length=10)
	song_title= models.CharField(max_length=250)
	is_favorite = models.BooleanField(default=False)

	def __str__(self):
		return self.song_title

music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForms(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from django.core.urlresolvers import reverse_lazy
from .models import Album
from .forms import UserForms

class IndexView(generic.ListView):
	template_name = 'music/index.html'
	context_object_name = 'album_list'

	def get_queryset(self):
		return Album.objects.all()

class DetailView(generic.DetailView):
	model = Album
	template_name = 'music/detail.html'

class AlbumCreate(CreateView):
	model = Album
	fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumUpdate(UpdateView):
	model = Album
	fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
	model = Album
	success_url = reverse_lazy('music:index')

class UserFormView(View):
	form_class = UserForms
	template_name = 'music/registration_form.html'

	# display blank form 
	def get(self, request):
		form = self.form_class(None)
		return render(request, self.template_name, {'form': form})

	# process form data
	def post(self, request):
		form = self.form_class(request.POST)

		if form.is_valid():

			user = form.save(commit=False)

			# clean (normalized) data
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user.set_password(password)
			user.save()

			# return user object if credentials are correc
			user = authenticate(username=username, password=password)

			if user is not None:

				if user.is_active:
					login(request, user)
					return redirect('music:index')
			
		return render(request, self.template_name, {'form': form})

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %} Add a New Album {% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
    <div  class="container-fluid">
        <div class="row">
            
            <div class="row">
                <div class="panel panel-default">
                    <div class="panel body">
                        
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'music/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    {% load staticfiles %}

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'music/css/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<!-- logo -->
		<div class="navbar-header">
			<button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#topNavBar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'music:index' %}">viberr</a>
		</div>

		<!-- items -->
		<div class="collapse navbar-collapse" id="topNavBar">
			<ul class="nav navbar-nav">
				<li class="active">
					<a href="{% url 'music:index' %}">
						<span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
					</a>	
				</li>
				<li class="">
					<a href="#">
						<span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
					</a>
				</li>
			</ul>

			<form class="navbar-form navbar-left" role="search" method="get" action"#">
				<div class="form-group">
					<input type="text" class="form-control" name="q" value="" />			
				</div>
				<button type="submit" class="btn btn-default">search</button>
			</form>
			<ul class="nav navbar-nav navbar-right">
				<li class="">
					<a href="{% url 'music:album-add' %}">
						<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
					</a>
				</li>
				<li class="">
					<a href="#">
						<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Log Out
					</a>
				</li>
			</ul>
		</div><!-- end items -->

	</div>
</nav> 
{% block body%}

{% endblock %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}

{% block title %}Details{% endblock %}

{% block body %}
<img src="{{album.album_logo.url}}" style="width: 250px; height: auto;">

<h1>{{ album.album_title }}</h1>
<h3>{{ album.artist }}</h3>

{% if error_message %}
    <p><strong>{{error_message}}</strong></p>
{% endif %}
<ul>
{% for song in album.song_set.all %}
   <li style="list-style-type: none;"> {{ song.song_title}}
    {% if song.is_favorite %}
        <img src="http://i.imgur.com/b9b13Rd.png" />
    {% endif %}
    </li>
{% endfor %}
</ul>
{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
       <div class="col-sm-offset-2 col-sm-10">
           <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block title%}Albums{% endblock %}

{% block body %}


		{% for album in album_list %}
			<div class="col-sm-4 col-lg-2">
				<div class="thumbnail">

					<!--album logo -->

					<a href="{% url 'music:detail' album.id %}">
						<img src="{{ album.album_logo.url }}" class="img-responsive">	
					</a>
					<div class="caption">
						<h2>{{album.album_title}}</h2>
						<h4>{{album.artist}}</h4>

						<!-- details -->
						<a href="{% url 'music:detail' album.id%}" class="btn btn-primary btn-sm">view details</a>
						
						<!-- delete -->
						<form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline;">
							{% csrf_token %}
							<input type="hidden" name="album_id" value="{{album.id}}" />
							<button type="submit" class="btn btn-default btn-sm">
								<span class="glyphicon glyphicon-trash"></span>
							</button>
						</form>

						<!-- favorite -->
						<a href="#" class="btn btn-default btn-sm btn-favorite">
							<span class="glyphicon glyphicon-star" {% if album.is_favorite %}active{% endif %}></span>
						</a>
					</div>
				</div>
			</div>
		{% endfor %}

{% endblock %}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %} Register {% endblock %}


{% block body %}
    <div  class="container-fluid">
        <div class="row">
            
            <div class="row">
                <div class="panel panel-default">
                    <div class="panel body">
                        <h3>Create New Account</h3>
                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'music/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}